---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    namespace_prefix: "<YOUR_NAME>"
    ci_cd_namespace: "{{ namespace_prefix }}-ci-cd"
    dev_namespace: "{{ namespace_prefix }}-dev"
    test_namespace: "{{ namespace_prefix }}-test"
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
