---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    ci_cd_namespace: <YOUR_NAME>-ci-cd
    dev_namespace: <YOUR_NAME>-dev
    test_namespace: <YOUR_NAME>-test
  
  roles:
    - { role: openshift-applier/roles/openshift-applier }
