---
ci_cd:
  NAMESPACE: "{{ namespace_prefix }}-ci-cd"
  NAMESPACE_DISPLAY_NAME: "{{ namespace_prefix}}s CI/CD"

dev:

test:

ansible_connection: local
openshift_cluster_content:
- object: projectrequest
  content:
  - name: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/project-requests.yml"
    action: create
    params_from_vars: "{{ ci_cd }}" 
    tags:
    - projects
